Add tests
triSYCL/sycl pull request #112
Opened 2021-03-10 12:34 UTC by Ralender

this is based on https://github.com/triSYCL/sycl/pull/111.

2021-03-10 23:10 UTC, keryell commented
Rename `kernel_arguement_forwarding.cpp` → `kernel_argument_forwarding.cpp`

2021-03-16 22:09 UTC, keryell requested changes
Rename kernel_arguement_forwarding.cpp → kernel_argument_forwarding.cpp
Also I wonder whether there is a need for a rebase. The changes seem huge...

2021-03-18 15:20 UTC, Ralender commented
addressed comments.

2021-03-19 01:01 UTC, keryell requested changes
Few details

2021-03-19 01:01 UTC, keryell commented on sycl/test/on-device/xocc/simple_tests/matmul.cpp
> +      print(G_rw);\
Strange

2021-03-19 01:01 UTC, keryell commented on sycl/test/on-device/xocc/simple_tests/matmul.cpp
> +    for (size_t j = 0; j < (size_t)output_r.get_range()[1]; j++) {
No tautological cast needed here https://www.khronos.org/registry/SYCL/specs/sycl-2020/html/sycl-2020.html#range-class

2021-03-19 01:01 UTC, keryell commented on sycl/test/on-device/xocc/simple_tests/matmul.cpp
> +    cgh.single_task<class S>([=]() {
While you are here...
```suggestion
    cgh.single_task<class S>([=] {
```

2021-03-19 01:01 UTC, keryell commented on sycl/test/on-device/xocc/simple_tests/variant.cpp
> +auto dev_visit(Func&& f, Var&& var, Rest&&... rest) {
You need to add a few comments on the various functions and explain why we need them at the first place

2021-03-19 01:01 UTC, keryell commented on sycl/test/on-device/xocc/simple_tests/variant.cpp
> +    cgh.single_task<class Kernel>([=]() {
```suggestion
    cgh.single_task<class Kernel>([=] {
```

2021-03-23 05:24 UTC, keryell approved these changes

2021-03-23 05:24 UTC, merged

2021-03-23 05:24 UTC, keryell commented
Thanks!