Add support for intel's pipes API when targeting Vitis
triSYCL/sycl pull request #183
Opened 2022-05-16 17:16 UTC by Ralender

this is based on the xrt_pi because it tested it with both the XRT and OpenCL backend.
but the last few commits are only pipe related.

2022-05-17 19:26 UTC, keryell commented
` [SYCL][Vitis] Add (parital) implementation of interprocedural rewrites.`: use a spell-checker

2022-05-18 00:43 UTC, keryell commented
To merge from next/rebase/conflict-resolve...

2022-05-20 17:07 UTC, keryell requested changes
Exciting!

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/KernelPropGen.cpp
> +  struct PipeEndpoint {
All this lacks comments.
For example, what represent the Kernel string or the Arg?
What means a depth of -1?
Etc.

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/KernelPropGen.cpp
> +  struct PipeEndpoint {
For example is Kernel the kernel name before or after Vitis-formatting?

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/KernelPropGen.cpp
> +            sycl::removePipeAnnotation(&Arg);
Say why

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/KernelProperties.cpp
>  bool KernelProperties::isArgBuffer(Argument *Arg, bool SyclHLSFlow) {
While you are here, add a top-level function comment

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/SYCLUtils.cpp
> +void annotateKernelFunc(Function *F) {
Add top comment. Not obvious for me to correlate the function name and the content.

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +    using pipe_creation_rec_t = std::pair<llvm::Function *, llvm::CallBase *>;
Why not just having a `struct` with some members with sensible names instead?

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +    std::string getTypeStr(Type* T) {
Better name to the function

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +    duplicateFunctionWithExtraArgs(llvm::Function *Orig, llvm::Function *Func,
This file starts to be quite big. I wonder whether we should move some code in some util/helper files.

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +      /// since it is rarely useful and not properly tested it is disable
```suggestion
      /// since it is rarely useful and not properly tested it is disabled
```

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +      /// Rewrite the all function and call that can transitively call Func
```suggestion
      /// Rewrite all the functions and calls that can transitively call Func
```

2022-05-20 17:07 UTC, keryell commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +      /// can be deleted by global dce
```suggestion
      /// This will not delete the old call graph but make it such that it
      /// can be deleted by global DCE
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +// REQUIRES: xocc
Rename `xocc`

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +#include <CL/sycl.hpp>
```suggestion
#include <sycl/sycl.hpp>
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +using PipeA = cl::sycl::ext::intel::pipe<class PipeNameA, int>;
```suggestion
using PipeA = sycl::ext::intel::pipe<class PipeNameA, int>;
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +    // sycl::host_accessor a_c(c);
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +      // a_c[i] = 0;
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +    // sycl::host_accessor a_b(b);
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +        // int res = i + i + 1;
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_complex_types.cpp
> +#include <CL/sycl.hpp>
```suggestion
#include <sycl/sycl.hpp>
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_complex_types.cpp
> +
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_complex_types.cpp
> +  using PipeA = cl::sycl::ext::intel::pipe<class PipeNameA, data>;
```suggestion
  using PipeA = sycl::ext::intel::pipe<class PipeNameA, data>;
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_complex_types.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_complex_types.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +// REQUIRES: xocc
Curious that the previous test did not have this

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +#include <CL/sycl.hpp>
```suggestion
#include <sycl/sycl.hpp>
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +    // sycl::host_accessor a_c(c);
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +      // a_c[i] = 0;
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +    // sycl::host_accessor a_b(b);
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +        // int res = i + i + 1;
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/tools/sycl-vxx/bin/sycl_vxx.py
> +        for pipe in self.kernel_properties['pipe_connections']:
Add a comment like `The pipe plumbing is actually done by Vitis with the right options`

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +#include <CL/sycl.hpp>
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +    // sycl::host_accessor a_c(c);
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +      // a_c[i] = 0;
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +    cgh.single_task([=]() {
```suggestion
    cgh.single_task([=] {
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +    // sycl::host_accessor a_b(b);
```suggestion
```

2022-05-20 17:07 UTC, keryell commented on sycl/test/vitis/simple_tests/pipe_multi_kernel.cpp
> +        // int res = a_a[i] + a_b[i];
```suggestion
```

2022-05-24 18:38 UTC, Ralender commented
it is not yet ready for review i am just transferring my WIP

2022-05-27 02:36 UTC, keryell requested changes
Thanks for the big cleaning.
A big moment of emotion with all the new comments! \o/

2022-05-27 02:36 UTC, keryell commented on llvm/lib/SYCL/KernelPropGen.cpp
> +  /// string matching the name of the global variable intel uses to identify its
```suggestion
  /// Pipes are matched in read and write pairs by their ID. Their ID is a
  /// string matching the name of the global variable Intel uses to identify its
```

2022-05-27 02:36 UTC, keryell commented on llvm/lib/SYCL/KernelPropGen.cpp
> +          /// remove them in the downgrader instead
```suggestion
          /// we use to annotate a pipe, so we remove it here. But we could
          /// remove them in the downgrader instead too.
```

2022-05-27 02:36 UTC, keryell commented on llvm/lib/SYCL/SYCLUtils.cpp
> +/// Pipe are represented with 3 sting attributes here are the names:
```suggestion
/// Pipe are represented with 3 string attributes with the following names:
```

2022-05-27 02:36 UTC, keryell commented on llvm/lib/SYCL/SYCLUtils.cpp
> +constexpr const char *xilinx_pipe_type =
```suggestion
constexpr auto xilinx_pipe_type =
```
everywhere?

2022-05-27 02:36 UTC, keryell commented on llvm/lib/SYCL/SYCLUtils.cpp
> +/// starts at 1
```suggestion
/// getAttributeAtIndex(0, ...) is the attribute on the return. The first argument
/// starts at 1
```
What about a *working* spell-checker for 2023? :-)
I am unsure my proposition is what you mean.

2022-05-27 02:36 UTC, keryell commented on sycl/test/vitis/edge_detection/edge_detection.cpp
> +#include <sysycl/sycl.hpp>
Does it work? :-)

2022-05-27 02:36 UTC, keryell commented on sycl/test/vitis/simple_tests/answer_42.cpp
> +#include <sysycl/sycl.hpp>
Gnih! Can you check everywhere?

2022-05-27 02:36 UTC, keryell commented on sycl/test/vitis/simple_tests/matmul.cpp
>                  output_r) {
Interestingly, then it breaks the indentation...

2022-05-27 02:36 UTC, keryell commented on sycl/test/vitis/simple_tests/multi_parallel_for.cpp
> +// kernels in the one translation unit when using Vitis HLS (xpirbc consumption
```suggestion
// kernels in the translation unit when using Vitis HLS (xpirbc consumption
```

2022-05-27 02:36 UTC, keryell commented on sycl/test/vitis/simple_tests/multi_parallel_for.cpp
> +// path doesn't allow you to pass -k all, each kernel needs to be compiled and
```suggestion
// pass doesn't allow you to pass -k all, each kernel needs to be compiled and
```

2022-05-31 16:58 UTC, Ralender commented
the version you reviewed wasnt the latest version. so some of the comments you had are outdated.

2022-05-31 19:46 UTC, Ralender commented on llvm/lib/SYCL/KernelProperties.cpp
>  bool KernelProperties::isArgBuffer(Argument *Arg, bool SyclHLSFlow) {
added in the header

2022-05-31 19:46 UTC, Ralender commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +    duplicateFunctionWithExtraArgs(llvm::Function *Orig, llvm::Function *Func,
This is function is specialized to the use case. so we should factorize it if we have a second use of something similar.

2022-05-31 19:46 UTC, Ralender commented on sycl/test/vitis/simple_tests/pipe_control_flow.cpp
> +// REQUIRES: xocc
it was a mistake

2022-06-01 16:09 UTC, Ralender commented
do not merge yet I started merging from upstream and this will be rebased on the merge

2022-06-01 16:39 UTC, keryell reviewed
Almost there!

2022-06-01 16:39 UTC, keryell commented on llvm/lib/SYCL/SYCLUtils.cpp
> +constexpr const char *xilinx_pipe_type =
`auto` seems enough everywhere.

2022-06-15 16:54 UTC, keryell commented
@Ralender ping!

2022-06-16 02:06 UTC, keryell approved these changes
Thanks!

2022-06-16 02:06 UTC, merged