[SYCL][XRT][Vitis] Fix some failling tests + improve device detection of xrt_pi
triSYCL/sycl pull request #185
Opened 2022-05-26 18:17 UTC by Ralender

2022-05-27 01:59 UTC, keryell requested changes
Thanks.
You can also fix the type in the commit message.

2022-05-27 01:59 UTC, keryell commented on sycl/plugins/xrt/pi_xrt.cpp
> +  /// _pi_platform hold a counting reference onto all its _pi_device so we do
```suggestion
  /// _pi_platform holds a counting reference onto all its _pi_device so we do
```

2022-05-27 01:59 UTC, keryell commented on sycl/plugins/xrt/pi_xrt.cpp
> +  std::vector<ref_counted_ref<_pi_device>> devices_;
I guess you need to update the comment accordingly.

2022-06-01 16:09 UTC, Ralender commented
do not merge yet I started merging from upstream and this will be rebased on the merge

2022-06-01 16:44 UTC, keryell requested changes
Looks good except the typo in the commit message: `failling` → `failling`.
But since you have to rebase this, you can edit the message at the same time.

2022-06-03 22:00 UTC, keryell approved these changes
Thanks!

2022-06-04 00:46 UTC, merged