Fixes next vitis
triSYCL/sycl pull request #191
Opened 2022-07-06 08:35 UTC by Ralender

This patch fixes some of the issues under the next version of vitis. also adds xrt_alloc which should be used when using xrt directly or not.

2022-07-08 17:50 UTC, keryell commented
I guess you need to rebase it on latest `sycl/unified/next` I have fixed.

2022-07-11 18:21 UTC, Ralender commented
here is the clean rebase

2022-07-25 21:23 UTC, keryell requested changes
You should clarify some points.

2022-07-25 21:23 UTC, keryell commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +    std::ignore = std::initializer_list<int>{(Args.push_back(ts), 0)...};
Why do you need this here but not on the previous line too?

2022-07-25 21:23 UTC, keryell commented on sycl/include/sycl/ext/xilinx/xrt_alloc.hpp
> +//
Explain somewhere why you need this.

2022-07-25 21:23 UTC, keryell commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +using namespace sycl;
I think you should not need this.

2022-07-25 21:23 UTC, keryell commented on llvm/lib/Transforms/Scalar/LoopUnrollPass.cpp
> +  cl::desc("Allow the loop remainder to be unrolled."));
Explain the rationale

2022-07-25 21:23 UTC, keryell commented on llvm/lib/Transforms/Utils/LowerMemIntrinsics.cpp
> +void annotateBackEdge(BranchInst *Br) {
Not clear what this does, considered the name of the function.

2022-07-26 00:25 UTC, Ralender commented
The review has not yet been addressed.

2022-07-26 18:34 UTC, Ralender reviewed
I added a commit to deal with terminate_xsim

2022-07-26 18:34 UTC, Ralender commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +    std::ignore = std::initializer_list<int>{(Args.push_back(ts), 0)...};
Why would I need what on the previous line ?

2022-07-26 18:34 UTC, Ralender commented on llvm/lib/Transforms/Scalar/LoopUnrollPass.cpp
> +  cl::desc("Allow the loop remainder to be unrolled."));
Hope the updated description helps

2022-07-26 18:34 UTC, Ralender commented on llvm/lib/Transforms/Utils/LowerMemIntrinsics.cpp
> +void annotateBackEdge(BranchInst *Br) {
is the new name more clear ?

2022-07-28 00:49 UTC, keryell commented on llvm/lib/IR/AutoUpgrade.cpp
> +  if (F->getIntrinsicID() == Intrinsic::not_intrinsic)
Why it was not the case before?
+ Comment.

2022-07-28 00:49 UTC, keryell commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +    (void)std::initializer_list<int>{(Args.push_back(ts), 0)...};
No more `std::ignore =`?

2022-07-28 00:49 UTC, keryell commented on llvm/lib/Transforms/Utils/LowerMemIntrinsics.cpp
> +void annotateBackEdge(BranchInst *Br) {
Yes.

2022-07-28 00:50 UTC, keryell reviewed
There are still some unanswered comments.

2022-07-28 18:20 UTC, Ralender commented on llvm/lib/SYCL/LowerSYCLMetaData.cpp
> +    (void)std::initializer_list<int>{(Args.push_back(ts), 0)...};
I prefer (void)

2022-07-28 18:20 UTC, Ralender commented on sycl/test/vitis/disabled/pipe_interprocedural.cpp
> +using namespace sycl;
This is the way it is for most tests.

2022-07-29 00:23 UTC, keryell requested changes
Almost there!

2022-07-29 00:23 UTC, keryell commented on sycl/include/sycl/ext/xilinx/xrt_alloc.hpp
> +// provides a sycl allocator with the proper alignment.
```suggestion
// When using Xilinx/AMD FPGA through the OpenCL backend, if buffer allocation
// are not aligned on 4096 bytes, XRT will perform an extra memcpy. This file
// provides a SYCL allocator with the proper alignment.
```

2022-08-02 00:07 UTC, keryell approved these changes
Thanks!

2022-08-02 00:08 UTC, merged